version: "3.9"

services:
  web:
    build: .
    command: bash -c "python /code/manage.py migrate; python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data
  celery:
    build: .
    command: celery -A project worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/code
  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - 5000:80
      - 2525:25
    restart: always

volumes:
  postgres_data:
  redisdata:
